// Generated by CoffeeScript 1.4.0
var MJState, ModelBase, MyPlayer, NPC, Plain, Player, Player1, Stage, Yama,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

ModelBase = (function() {

  function ModelBase() {
    this.listeners = [];
  }

  ModelBase.prototype.add_listener = function(a) {
    this.listeners.push(a);
    return a;
  };

  ModelBase.prototype.notify = function(action) {
    var i, _i, _len, _ref, _results;
    _ref = this.listeners;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      _results.push(i.update(this, action));
    }
    return _results;
  };

  ModelBase.prototype.remove_listener = function(a) {
    return this.listeners.splice(this.listeners.indexOf(a), 1);
  };

  return ModelBase;

})();

Stage = (function(_super) {

  __extends(Stage, _super);

  function Stage() {
    var i, _i;
    Stage.__super__.constructor.apply(this, arguments);
    this.statuslist = {
      start_kyoku: 0,
      tsumo: 1,
      dahai: 2,
      other_player: 3,
      wait_for_response: 4
    };
    this.status = this.statuslist.start_kyoku;
    this.action_que = [];
    this.ActionSortIndex = {
      hora: 0,
      pon: 1,
      kan: 2,
      chi: 3,
      none: 4
    };
    this.players = [];
    for (i = _i = 0; _i <= 3; i = ++_i) {
      if (i === 0) {
        this.players.push(new MyPlayer(i, i));
      } else {
        this.players.push(new NPC(i, i));
      }
    }
    this.kyoku = 1;
    this.titya = 0;
    this.oya = this.titya;
    this.honba = 0;
    this.bakaze = 0;
    this.kyotaku = 0;
  }

  Stage.prototype.update = function() {
    var a;
    switch (this.status) {
      case 0:
        a = this.wait_for_start();
        break;
      case 1:
        a = this.wait_for_tsumo();
        break;
      case 2:
        a = this.wait_for_dahai();
        break;
      case 3:
        a = this.wait_for_other_player();
    }
    if (a) {
      this.act(a);
      return a;
    }
  };

  Stage.prototype.wait_for_start = function() {
    var a, i, j, _i, _j;
    this.yama = new Yama;
    this.yama.shuffle();
    this.wanpai = this.yama.pop_wanpai();
    a = {
      "type": "start_kyoku",
      "bakaze": this.bakaze,
      "kyoku": this.kyoku,
      "honba": this.honba,
      "kyotaku": this.kyotaku,
      "oya": this.oya,
      "dora_marker": this.wanpai[0],
      "tehais": [[], [], [], []]
    };
    for (i = _i = 0; _i < 4; i = ++_i) {
      for (j = _j = 0; _j < 13; j = ++_j) {
        a.tehais[i].push(this.yama.shift());
      }
    }
    return a;
  };

  Stage.prototype.wait_for_tsumo = function() {
    if (this.yama.length() === 0) {
      return {
        type: "ryukyoku"
      };
    } else {
      return {
        type: "tsumo",
        actor: this.now_player,
        pai: this.yama.shift()
      };
    }
  };

  Stage.prototype.wait_for_dahai = function() {
    if (this.now_player.action) {
      return this.now_player.pop_action();
    }
  };

  Stage.prototype.wait_for_other_player = function() {
    var a, i, p, _i, _len, _ref,
      _this = this;
    _ref = this.players.filter(function(i) {
      return i !== _this.now_player;
    });
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      if (i.action) {
        this.action_que.push(i.pop_action());
      }
    }
    if (this.action_que.length < 3) {
      return;
    }
    this.action_que.sort(function(a, b) {
      var diff;
      diff = _this.ActionSortIndex[a.type] - _this.ActionSortIndex[b.type];
      if (diff !== 0 || a.type === "none") {
        return diff;
      } else {
        return _this.now_player.get_distance(a.actor) - _this.now_player.get_distance(b.actor);
      }
    });
    a = this.action_que[0];
    if (a.type !== "hora") {
      if (this.reached_player !== false) {
        p = this.reached_player;
        this.reached_player = false;
        return {
          type: "reach_accepted",
          actor: p
        };
      }
    }
    this.action_que.length = 0;
    return a;
  };

  Stage.prototype.act = function(a) {
    var _this = this;
    switch (a.type) {
      case "start_kyoku":
        this.start(a);
        this.status = this.statuslist.tsumo;
        break;
      case "tsumo":
        this.turn++;
        a.actor.tsumo(a);
        this.status = this.statuslist.dahai;
        break;
      case "hora":
        a.actor.hora(a);
        this.agari(a);
        this.end_kyoku(a);
        this.status = this.statuslist.start_kyoku;
        return;
      case "reach":
        a.actor.reach_naki_count = this.naki_count;
        this.reached_player = a.actor;
        break;
      case "reach_accepted":
        a.actor.reach_accepted(a);
        this.kyotaku++;
        a.actor.score -= 1000;
        break;
      case "dahai":
        a.actor.dahai(a);
        this.players.filter(function(i) {
          return i !== a.actor;
        }).forEach(function(i) {
          return i.ask(a);
        });
        this.status = this.statuslist.other_player;
        break;
      case "pon":
        a.actor.pon(a);
        this.phase_set(a.actor.number);
        this.status = this.statuslist.dahai;
        break;
      case "chi":
        a.actor.chi(a);
        this.phase_set(a.actor.number);
        this.status = this.statuslist.dahai;
        break;
      case "kan":
        if (a.target === a.actor) {
          a.actor.kan(a);
        } else {
          a.actor.minkan(a);
          this.phase_set(a.actor.number);
          this.status = this.statuslist.dahai;
        }
        break;
      case "none":
        this.next_phase();
        this.status = this.statuslist.tsumo;
        break;
      case "ryukyoku":
        this.end_kyoku(a);
        this.status = this.statuslist.start_kyoku;
    }
    if (a.type === "pon" || a.type === "chi" || a.type === "kan") {
      this.naki_count++;
    }
    this.notify(a);
    return a;
  };

  Stage.prototype.start = function(a) {
    var i, j, n, _i, _j, _len, _len1, _ref, _ref1, _results;
    this.action_que.length = 0;
    _ref = this.players;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      i.set_kyoku();
      i.state = new MJState(i, this);
      i.checker = new HaiChecker(i.state);
    }
    this.kan_count = 0;
    this.wanpai = [];
    this.doras = [];
    this.uradoras = [];
    this.reachbou = [0, 0, 0, 0];
    this.phase_set(a.oya);
    this.naki_count = 0;
    this.bakaze = a.bakaze;
    this.kyoku = a.kyoku;
    this.honba = a.honba;
    this.doras = [a.dora_marker];
    this.reached_player = false;
    _ref1 = a.tehais;
    _results = [];
    for (n = _j = 0, _len1 = _ref1.length; _j < _len1; n = ++_j) {
      i = _ref1[n];
      _results.push((function() {
        var _k, _len2, _results1;
        _results1 = [];
        for (_k = 0, _len2 = i.length; _k < _len2; _k++) {
          j = i[_k];
          _results1.push(this.players[n].push_tehai(j));
        }
        return _results1;
      }).call(this));
    }
    return _results;
  };

  Stage.prototype.next_phase = function() {
    return this.phase_set(this.phase + 1);
  };

  Stage.prototype.end_kyoku = function(end_reason) {
    var flag, i, sum, ten, _i, _j, _len, _len1, _ref, _ref1;
    this.end_reason_settigs || (this.end_reason_settigs = {
      0: ["hora", "nagasimangan"],
      1: ["ryukyoku"]
    });
    switch (end_reason.type) {
      case "hora":
        if (end_reason.actor.is_oya()) {
          this.honba++;
        } else {
          this.next_kyoku();
        }
        break;
      case "ryukyoku":
        this.notify({
          type: "ryukyoku"
        });
        sum = 0;
        flag = false;
        _ref = this.players;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          if (i.tenpai()) {
            sum++;
          }
        }
        ten = [[0, 0], [3000, 1000], [1500, 1500], [1000, 3000], [0, 0]];
        _ref1 = this.players;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          i = _ref1[_j];
          if (i.tenpai()) {
            i.score += ten[sum][0];
          } else {
            i.score -= ten[sum][1];
          }
          if (i.is_oya()) {
            flag = i.tenpai();
          }
        }
        if (flag) {
          this.honba++;
        } else {
          this.next_kyoku();
        }
    }
    return this.notify({
      type: "end_kyoku"
    });
  };

  Stage.prototype.agari = function(a) {
    var agari, b, i, _i, _len;
    if (!a.hasOwnProperty("deltas")) {
      agari = a.actor.get_agari();
    }
    if (a.actor === a.target) {
      b = this.players.filter(function(i) {
        return i !== a.actor;
      });
      for (_i = 0, _len = b.length; _i < _len; _i++) {
        i = b[_i];
        if (i.is_oya()) {
          i.score -= agari.scores[1];
          a.actor.score += agari.scores[1];
        } else {
          i.score -= agari.scores[0];
          a.actor.score += agari.scores[0];
        }
      }
    } else {
      a.target.score -= agari.score;
      a.actor.score += agari.score;
      if (this.kyotaku !== 0) {
        a.actor.score += this.kyotaku * 1000;
        this.kyotaku = 0;
      }
    }
    return this.notify(a);
  };

  Stage.prototype.phase_set = function(a) {
    this.phase = a % 4;
    return this.now_player = this.players[this.phase];
  };

  Stage.prototype.get_titya = function() {
    return this.players[this.titya];
  };

  Stage.prototype.next_kyoku = function() {
    var i, _i, _j, _len, _ref;
    this.honba = 0;
    this.kyoku++;
    if (this.kyoku > 5) {
      this.kyoku = 1;
      this.bakaze++;
      if (this.bakaze > 4) {
        this.players = [];
        for (i = _i = 0; _i <= 3; i = ++_i) {
          if (i === 0) {
            this.players.push(new MyPlayer(i, i));
          } else {
            this.players.push(new NPC(i, i));
          }
        }
        this.kyoku = 1;
        this.titya = 0;
        this.oya = this.titya;
        this.honba = 0;
        this.bakaze = 0;
        this.kyotaku = 0;
        return;
      }
    }
    _ref = this.players;
    for (_j = 0, _len = _ref.length; _j < _len; _j++) {
      i = _ref[_j];
      i.kaze = (i.kaze + 1) % 4;
    }
    return this.oya = (this.oya + 1) % 4;
  };

  return Stage;

})(ModelBase);

Yama = (function() {

  function Yama() {
    var _i, _j, _k, _l, _results, _results1, _results2, _results3;
    this.a = (function() {
      _results3 = [];
      for (_l = 0; _l <= 33; _l++){ _results3.push(_l); }
      return _results3;
    }).apply(this).concat((function() {
      _results = [];
      for (_i = 0; _i <= 33; _i++){ _results.push(_i); }
      return _results;
    }).apply(this), (function() {
      _results1 = [];
      for (_j = 0; _j <= 33; _j++){ _results1.push(_j); }
      return _results1;
    }).apply(this), (function() {
      _results2 = [];
      for (_k = 0; _k <= 33; _k++){ _results2.push(_k); }
      return _results2;
    }).apply(this));
    this.count2 = 0;
  }

  Yama.prototype.shift = function() {
    return this.a.shift();
  };

  Yama.prototype.unshift = function() {
    return this.a.unshift();
  };

  Yama.prototype.get = function() {
    return this.a;
  };

  Yama.prototype.shuffle = function() {
    return this.a = this.a.shuffle();
  };

  Yama.prototype.length = function() {
    return this.a.length;
  };

  Yama.prototype.pop_wanpai = function() {
    var w;
    w = this.a.slice(124, 132);
    this.a.splice(124, 14);
    return w;
  };

  Yama.prototype.tsumikomi = function(pais) {
    var i, _i, _j, _len, _len1, _results;
    for (_i = 0, _len = pais.length; _i < _len; _i++) {
      i = pais[_i];
      this.a.splice(this.a.indexOf(i), 1);
    }
    _results = [];
    for (_j = 0, _len1 = pais.length; _j < _len1; _j++) {
      i = pais[_j];
      _results.push(this.a.unshift(i));
    }
    return _results;
  };

  return Yama;

})();

MJState = (function() {

  function MJState(player, stage) {
    this.player = player;
    this.stage = stage;
  }

  MJState.prototype.doras = function() {
    if (!this.player.reach) {
      return this.stage.doras;
    } else {
      return this.stage.doras.concat(this.stage.uradoras);
    }
  };

  MJState.prototype.dora_count = function() {
    return 0;
  };

  MJState.prototype.honba = function() {
    return this.stage.honba;
  };

  MJState.prototype.reachbou = function() {
    return this.stage.reachbou.reduce(function(x, y) {
      return x + y;
    });
  };

  MJState.prototype.yakuhai = function(h) {
    return (30 < h && h < 34) || this.jikaze(h) || this.bakaze(h);
  };

  MJState.prototype.jikaze = function(h) {
    return h === 27 + this.player.kaze;
  };

  MJState.prototype.bakaze = function(h) {
    return h === 27 + this.stage.bakaze;
  };

  MJState.prototype.get_yama_length = function() {
    return this.stage.yama.length();
  };

  MJState.prototype.menzen = function() {
    return this.player.menzen;
  };

  MJState.prototype.tsumo = function() {
    return this.player.tsumohai;
  };

  MJState.prototype.reach = function() {
    return this.player.reach;
  };

  MJState.prototype.reach_count = function() {
    return this.player.reach_count;
  };

  MJState.prototype.is_oya = function() {
    return this.player.is_oya();
  };

  MJState.prototype.is_doublereach = function() {
    return this.stage.naki_count === 0 && this.player.kawa.length === 0;
  };

  MJState.prototype.is_ippatsu = function() {
    return this.player.reach_kawa_count === 0 && this.player.reach_naki_count === this.stage.naki_count;
  };

  return MJState;

})();

Player = (function(_super) {

  __extends(Player, _super);

  function Player(n, k) {
    Player.__super__.constructor.call(this);
    this.number = n;
    this.kaze = k;
    this.score = 25000;
    this.set_kyoku();
  }

  Player.prototype.set_action = function(a) {
    this.action = a;
    this.last_action = a;
    if (a) {
      return console.log(a);
    }
  };

  Player.prototype.pop_action = function() {
    var a;
    a = this.action;
    this.set_action(false);
    return a;
  };

  Player.prototype.set_kyoku = function() {
    this.set_action(false);
    this.reach = false;
    this.reach_kawa_count = 0;
    this.reach_naki_count = 0;
    this.menzen = true;
    this.tsumohai = null;
    this.tehai = [];
    return this.kawa = [];
  };

  Player.prototype.push_tehai = function(h) {
    return this.tehai.push(h);
  };

  Player.prototype.push_kawa = function(h) {
    return this.kawa.push(h);
  };

  Player.prototype.pop_kawa = function() {};

  Player.prototype.tsumo = function(a) {
    this.push_tehai(a.pai);
    return this.tsumohai = a.pai;
  };

  Player.prototype.dahai = function(a) {
    this.tehai.splice(this.tehai.indexOf(a.pai), 1);
    this.kawa.push(a.pai);
    this.tsumohai = false;
    if (this.reach) {
      return this.reach_kawa_count++;
    }
  };

  Player.prototype.reach_accepted = function(a) {
    return this.reach = true;
  };

  Player.prototype.ask = function(a) {
    this.target_pai = a.pai;
    return this.target_player = a.actor;
  };

  Player.prototype.pon = function(a) {
    return this.menzen = false;
  };

  Player.prototype.chi = function(a) {
    return this.menzen = false;
  };

  Player.prototype.hora = function(a) {};

  Player.prototype.kan = function(a) {};

  Player.prototype.daiminkan = function(a) {
    return this.menzen = false;
  };

  Player.prototype.kakan = function(a) {};

  Player.prototype.is_oya = function() {
    return this.kaze === 0;
  };

  Player.prototype.get_agari = function() {
    return null;
  };

  Player.prototype.can_agari = function() {
    return false;
  };

  Player.prototype.can_ron = function(h) {
    return false;
  };

  Player.prototype.can_pon = function(h) {
    return false;
  };

  Player.prototype.can_chi = function(h) {
    return false;
  };

  Player.prototype.can_kan = function(h) {
    return false;
  };

  Player.prototype.can_reach = function() {
    return false;
  };

  Player.prototype.tenpai = function() {
    return false;
  };

  Player.prototype.get_distance = function(player) {
    var a;
    a = this.number - player.number;
    if (a > 0) {
      return a;
    } else {
      return a + 4;
    }
    return 0;
  };

  return Player;

})(ModelBase);

Player1 = (function(_super) {

  __extends(Player1, _super);

  function Player1() {
    return Player1.__super__.constructor.apply(this, arguments);
  }

  Player1.prototype.push_tehai = function(pai) {
    Player1.__super__.push_tehai.apply(this, arguments);
    return this.checker.push_tehai(pai);
  };

  Player1.prototype.tsumo = function(a) {
    this.push_tehai(a.pai);
    this.tsumohai = a.pai;
    return this.checker.check_agari();
  };

  Player1.prototype.dahai = function(a) {
    Player1.__super__.dahai.apply(this, arguments);
    return this.checker.remove(a.pai);
  };

  Player1.prototype.get_agari = function() {
    return this.checker.get_actually_score();
  };

  Player1.prototype.can_agari = function() {
    return this.checker.can_agari();
  };

  Player1.prototype.can_ron = function() {
    var _ref;
    this.checker.check_agari();
    if (_ref = this.target_pai, __indexOf.call(this.checker.machis.map(function(i) {
      return i[0];
    }), _ref) >= 0) {
      return this.checker.machis.map(function(i) {
        return i[1];
      });
    }
  };

  Player1.prototype.can_pon = function() {
    if (this.checker.can_pon(this.target_pai) && !this.reach) {
      return [this.target_pai];
    }
  };

  Player1.prototype.can_chi = function() {
    if (this.get_distance(this.target_player) === 1 && !this.reach) {
      return this.checker.can_chi(this.target_pai);
    }
  };

  Player1.prototype.can_reach = function() {
    if (this.checker.machis.length !== 0 && this.menzen && !this.reach) {
      return this.checker.machis.map(function(i) {
        return i[1];
      });
    }
  };

  Player1.prototype.hora = function(a) {
    Player1.__super__.hora.apply(this, arguments);
    if (a.target !== this) {
      this.checker.push_tehai(a.pai);
      return this.checker.check_agari();
    }
  };

  Player1.prototype.tenpai = function() {
    return this.checker.machis.length !== 0;
  };

  Player1.prototype.pon = function(a) {
    Player1.__super__.pon.apply(this, arguments);
    return this.checker.naki(a.pai, a.consumed);
  };

  Player1.prototype.chi = function(a) {
    Player1.__super__.chi.apply(this, arguments);
    return this.checker.naki(a.pai, a.consumed);
  };

  Player1.prototype.kan = function(a) {
    Player1.__super__.kan.apply(this, arguments);
    return this.checker.kan(a.pai, a.consumed);
  };

  Player1.prototype.daiminkan = function(a) {
    Player1.__super__.daiminkan.apply(this, arguments);
    return this.checker.daiminkan(a.pai, a.consumed);
  };

  return Player1;

})(Player);

MyPlayer = (function(_super) {

  __extends(MyPlayer, _super);

  function MyPlayer() {
    return MyPlayer.__super__.constructor.apply(this, arguments);
  }

  MyPlayer.prototype.set_action = function(a) {
    MyPlayer.__super__.set_action.apply(this, arguments);
    if (a) {
      return this.notify({
        type: "selected",
        action: a,
        actor: this
      });
    }
  };

  return MyPlayer;

})(Player1);

NPC = (function(_super) {

  __extends(NPC, _super);

  function NPC() {
    return NPC.__super__.constructor.apply(this, arguments);
  }

  NPC.prototype.ask = function(a) {
    NPC.__super__.ask.apply(this, arguments);
    return this.set_action({
      type: "none",
      actor: this
    });
  };

  NPC.prototype.tsumo = function(a) {
    NPC.__super__.tsumo.apply(this, arguments);
    return this.set_action({
      type: "dahai",
      pai: a.pai,
      index: 13,
      actor: this
    });
  };

  return NPC;

})(Player1);

Plain = (function(_super) {

  __extends(Plain, _super);

  function Plain() {
    return Plain.__super__.constructor.apply(this, arguments);
  }

  return Plain;

})(Player);
